// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbi1YqXzGPIv2ju-xWYOc1mSOReGDf5Y4',
    appId: '1:744211779809:web:4b3bdb567859f7e6ef67a0',
    messagingSenderId: '744211779809',
    projectId: 'socialapp-57090',
    authDomain: 'socialapp-57090.firebaseapp.com',
    storageBucket: 'socialapp-57090.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxU9y9zamhJKWvDNhzXpMip7a3soXq-KI',
    appId: '1:744211779809:android:d0653123db7ca2c1ef67a0',
    messagingSenderId: '744211779809',
    projectId: 'socialapp-57090',
    storageBucket: 'socialapp-57090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgd8EEKMXvnxQM9EPOlJ41AxsVbXnExII',
    appId: '1:744211779809:ios:da0fdaf1d5cfd4f4ef67a0',
    messagingSenderId: '744211779809',
    projectId: 'socialapp-57090',
    storageBucket: 'socialapp-57090.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgd8EEKMXvnxQM9EPOlJ41AxsVbXnExII',
    appId: '1:744211779809:ios:1ad7bf3650f73092ef67a0',
    messagingSenderId: '744211779809',
    projectId: 'socialapp-57090',
    storageBucket: 'socialapp-57090.appspot.com',
    iosBundleId: 'com.example.loginSignup.RunnerTests',
  );
}
